
version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dialog
      POSTGRES_USER: dialog
      POSTGRES_PASSWORD: dialog
    ports: ["5432:5432"]
    volumes:
      - ../postgres/init:/docker-entrypoint-initdb.d
<<<<<<< HEAD
=======

  api:
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://dialog:dialog@postgres:5432/dialog
      PYTHONUNBUFFERED: "1"
    ports: ["8080:8080"]
    depends_on: [postgres]
>>>>>>> ecf301c (api skeleton)
