
version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dialog
      POSTGRES_USER: dialog
      POSTGRES_PASSWORD: dialog
    ports: ["5432:5432"]
    volumes:
      - ../postgres/init:/docker-entrypoint-initdb.d
