
name: "dialog_sql_dbt"
version: "1.0.0"
config-version: 2

profile: "dialog_sql"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dialog_sql_dbt:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
