
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'
      - run: poetry install --no-interaction
      - run: poetry run black --check .
      - run: poetry run isort --check-only .
      - run: poetry run flake8 services tests
      - run: poetry run mypy services/api/app
      - run: poetry run pytest -q
